name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  nuitka:
    runs-on: windows-latest
    steps:
      - name: Setup Time Zone
        run: tzutil /s "China Standard Time"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build with Nuitka
        shell: cmd
        run: |
          nuitka ^
            --standalone ^
            --onefile ^
            --windows-uac-admin ^
            --assume-yes-for-downloads ^
            --output-dir=nuitka_out ^
            --output-filename=douyin-rtmp-nuitka.exe ^
            main.py

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: douyin-rtmp-nuitka
          path: ${{ github.workspace }}/nuitka_out/douyin-rtmp-nuitka.exe

  release:
    needs: [nuitka]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - name: Download Nuitka artifact
        uses: actions/download-artifact@v4
        with:
          name: douyin-rtmp-nuitka
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            douyin-rtmp-nuitka.exe
          draft: true
          prerelease: false
          generate_release_notes: true
          make_latest: false
